name: Build BlissOS18 typhoon-x86 Emu-GApps ISO
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          swap-size-gb: 16

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y git repo gnupg flex bison gperf build-essential zip \
          curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses-dev \
          x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python-is-python3

      - name: Init & Sync Repo
        run: |
          mkdir -p bliss && cd bliss
          repo init -u https://github.com/BlissOS/platform_manifest.git -b typhoon-x86
          repo sync -c --force-sync --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc)
          repo forall -c git lfs pull

      - name: Build GApps ISO
        run: |
          cd bliss
          . build/envsetup.sh
          lunch android_x86_64-userdebug
          export BLISS_BUILD_VARIANT=gapps
          make iso_img -j$(nproc)

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: BlissOS18-typhoon-x86_64-EmuGApps-ISO
          path: bliss/out/target/product/x86_64/*.iso
